iglesia/src/EMM/UserBundle/Entity/Task.php
<?php

namespace EMM\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Task
 *
 * @ORM\Table(name="tasks")
 * @ORM\Entity(repositoryClass="EMM\UserBundle\Repository\TaskRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Task
{
    
     /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="tasks")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", onDelete="CASCADE")
     */ 
    protected $user;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=100)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     */
    private $description;

    /**
     * @var bool
     *
     * @ORM\Column(name="status", type="boolean")
     */
    private $status;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime")
     */
    private $updatedAt;
     

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Task
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Task
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set status
     *
     * @param boolean $status
     * @return Task
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return boolean 
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Task
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     * @return Task
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    
    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    
    
    public function setUpdatedAtValue()/* fecha la hora correspondiente ala que se va a tuilizar*/
    {
        $this->updatedAt =new \DateTime();/* esto se setea en prepersist y tambien adiciamente preudate en el cmomento que actualizemos o modifquemos uno de nuestros registrso*/

        return $this;
    }
    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue( )/*va a sestiar nuestra fecha actual a la que se esta registrarse*/
    {
        $this->createdAt = new \DateTime();/*al momento qaue perssiste , setea por eso prepersisit*/

        return $this;
    }
    
    /**
     * Get updatedAt
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set user
     *
     * @param \EMM\UserBundle\Entity\User $user
     * @return Task
     */
    public function setUser(\EMM\UserBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \EMM\UserBundle\Entity\User 
     */
    public function getUser()
    {
        return $this->user;
    }
}

iglesia/src/EMM/UserBundle/Entity/User.php
<?php

namespace EMM\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;

/**
 * User
 *
 * @ORM\Table(name="users")
 * @ORM\Entity(repositoryClass="EMM\UserBundle\Repository\UserRepository")
 * @UniqueEntity("username")
 * @UniqueEntity("email")
 * @ORM\HasLifecycleCallbacks()
 */
class User implements AdvancedUserInterface, \Serializable
{
    /**
     * @ORM\OneToMany(targetEntity="Task", mappedBy="user")
     * @ORM\OneToMany(targetEntity="Archivo",mappedBy="user")
     * * @ORM\OneToMany(targetEntity="Comentario",mappedBy="user")
     */ 
    
    protected $comentarios;
protected $tasks;
 protected $archivos;   
   
    
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="username", type="string", length=50)
     * @Assert\NotBlank(message="user.username.not_blank")
     */
    private $username;

    /**
     * @var string
     *
     * @ORM\Column(name="first_name", type="string", length=100)
     * @Assert\NotBlank()
     */
    private $firstName;

    /**
     * @var string
     *
     * @ORM\Column(name="lsta_name", type="string", length=100)
     * @Assert\NotBlank()
     */
    private $lstaName;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=100)
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=255)
     *
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(name="role", type="string",columnDefinition="ENUM('ROLE_ADMIN','ROLE_USER')", length=50)
     * @Assert\NotBlank()
     * @Assert\Choice(choices = {"ROLE_ADMIN", "ROLE_USER"})
     */
    private $role;

    /**
     * @var bool
     *
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     */
    
     
    
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime")
     */
    private $updatedAt;
    
    
        public function __construct()
    {
        $this->tasks = new ArrayCollection();
        $this->isActive=true;
        $this->archivos=new ArrayCollection();
    }


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set username
     *
     * @param string $username
     * @return User
     */
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Get username
     *
     * @return string 
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set firstName
     *
     * @param string $firstName
     * @return User
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Get firstName
     *
     * @return string 
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Set lstaName
     *
     * @param string $lstaName
     * @return User
     */
    public function setLstaName($lstaName)
    {
        $this->lstaName = $lstaName;

        return $this;
    }

    /**
     * Get lstaName
     *
     * @return string 
     */
    public function getLstaName()
    {
        return $this->lstaName;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return User
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set password
     *
     * @param string $password
     * @return User
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string 
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Set role
     *
     * @param string $role
     * @return User
     */
    public function setRole($role)
    {
        $this->role = $role;

        return $this;
    }

    /**
     * Get role
     *
     * @return string 
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Set isActive
     *
     * @param boolean $isActive
     * @return User
     */
    public function setIsActive($isActive)
    {
        $this->isActive = $isActive;

        return $this;
    }

    /**
     * Get isActive
     *
     * @return boolean 
     */
    public function getIsActive()
    {
        return $this->isActive;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return User
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     * @return User
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }
    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    
    
    public function setUpdatedAtValue()/* fecha la hora correspondiente ala que se va a tuilizar*/
    {
        $this->updatedAt =new \DateTime();/* esto se setea en prepersist y tambien adiciamente preudate en el cmomento que actualizemos o modifquemos uno de nuestros registrso*/

        return $this;
    }
    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue( )/*va a sestiar nuestra fecha actual a la que se esta registrarse*/
    {
        $this->createdAt = new \DateTime();/*al momento qaue perssiste , setea por eso prepersisit*/

        return $this;
    }
    
   
    public function getRoles()
    {
        return array($this->role);
    }
    
    public function getSalt()
    {
        return null;
    }
    
    public function eraseCredentials()
    {
        
}

    /**
     * Add tasks
     *
     * @param \EMM\UserBundle\Entity\Task $tasks
     * @return User
     */
    public function addTask(\EMM\UserBundle\Entity\Task $tasks)
    {
        $this->tasks[] = $tasks;

        return $this;
    }

    /**
     * Remove tasks
     *
     * @param \EMM\UserBundle\Entity\Task $tasks
     */
    public function removeTask(\EMM\UserBundle\Entity\Task $tasks)
    {
        $this->tasks->removeElement($tasks);
    }

    /**
     * Get tasks
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getTasks()
    {
        return $this->tasks;
    }
    public function getFullName(){
        return $this->firstName." ".$this->lstaName;
    }
    
    
    
    
     /**
     * Add archivos
     *
     * @param \EMM\UserBundle\Entity\Archivo $archivos
     * @return User
     */
    public function addArchivo(\EMM\UserBundle\Entity\Archivo $archivos)
    {
        $this->archivos[] = $archivos;

        return $this;
    }

    /**
     * Remove archivos
     *
     * @param \EMM\UserBundle\Entity\Archivo $archivos
     */
    public function removeArchivo(\EMM\UserBundle\Entity\Archivo $archivos)
    {
        $this->archivos->removeElement($archivos);
    }

    /**
     * Get archivos
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getArchivos()
    {
        return $this->archivos;
    }
    
    
    
    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            $this->isActive
        ));
    }
    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->password,
            $this->isActive
        ) = unserialize($serialized);
    }   
    
     public function isAccountNonExpired()
    {
        return true;
    }
    public function isAccountNonLocked()
    {
        return true;
    }
    public function isCredentialsNonExpired()
    {
        return true;
    }
    public function isEnabled()
    {
        return $this->isActive;
    }

    /**
     * Add comentarios
     *
     * @param \EMM\UserBundle\Entity\Task $comentarios
     * @return User
     */
    public function addComentario(\EMM\UserBundle\Entity\Task $comentarios)
    {
        $this->comentarios[] = $comentarios;

        return $this;
    }

    /**
     * Remove comentarios
     *
     * @param \EMM\UserBundle\Entity\Task $comentarios
     */
    public function removeComentario(\EMM\UserBundle\Entity\Task $comentarios)
    {
        $this->comentarios->removeElement($comentarios);
    }

    /**
     * Get comentarios
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getComentarios()
    {
        return $this->comentarios;
    }
    
        public function __toString()
{
  return   $this->getUsername();
}
}

iglesia/src/EMM/UserBundle/Form/TaskType.php
<?php

namespace EMM\UserBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Doctrine\ORM\EntityRepository;
class TaskType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
                ->add('title')
                ->add('description')
                ->add('user','entity',array('class'=>'EMMUserBundle:User','query_builder'=>function(EntityRepository $er){
                            return $er->createQueryBuilder('u')
                                    ->where('u.role=:only')
                                    ->setParameter('only','ROLE_USER');
            
            
                },
                'choice_label'=>'getFullName'/*idea mostrar un selecbox, en ese campo mostramos el nombre compuesto*/
                    
                    
                    
                    
                    
                    ))
                 ->add('save','submit',array('label'=>'Save task'))        ;
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'EMM\UserBundle\Entity\Task'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'task';
    }


}

iglesia/src/EMM/UserBundle/Resources/views/Task/add.html.twig
{% extends 'layout.html.twig' %}

{% block body %}
    {{ parent() }}
	<div class="main container">
		<div class="row well">
			<div class="col-md-6">
				<div class="page-header">
					<h2>{% trans %}New task{% endtrans %}</h2>
				</div>
				{{ form_start(form, {'attr': {'novalidate': 'novalidate', 'role' : 'form'}}) }}
				    <h4 class="text-danger">{{ form_errors(form) }}</h4>

					<fieldset>
					    <div class="form-group">
					        {{ form_label(form.title) }}
					        {{ form_widget(form.title, {'attr': {'class': 'form-control', 'placeholder' : 'Task title'}}) }}
					        <span class="text-danger">{{ form_errors(form.title) }}</span>
					    </div>

					    <div class="form-group">
					        {{ form_label(form.user) }}
					        {{ form_widget(form.user, {'attr': {'class': 'form-control'}}) }}
					        <span class="text-danger">{{ form_errors(form.user) }}</span>
					    </div>

					    <div class="form-group">
					        {{ form_label(form.description) }}
					        {{ form_widget(form.description, {'attr': {'class': 'form-control', 'placeholder' : 'Task description'}}) }}
					        <span class="text-danger">{{ form_errors(form.description) }}</span>
					    </div>
					</fieldset>

				    <p>
				        {{ form_widget(form.save, {'label' : 'Create task', 'attr': {'class': 'btn btn-success'}}) }}
				    </p>

				{{ form_end(form) }}
			</div>
		</div>
	</div>
{% endblock %}

iglesia/src/EMM/UserBundle/Resources/views/Task/custom.html.twig
{% extends 'layout.html.twig' %}

{% block body %}
	{{ parent() }}

	{{ include('EMMUserBundle:Task:messages/success.html.twig') }}
        {{ include('EMMUserBundle:Task:messages/warning.html.twig') }}
	

	<div class="container">
		<div class="col-md-12">
			<div class="page-header margin-none">
				<h2 class="padding-none">{{ 'Tasks'|trans }}</h2>
			</div>
			{% if not pagination|length %}
				<h3>{{ 'No tasks'|trans }}</h3>
			{% endif %}
			{% if pagination|length %}
			<div class="table-responsive">
				<p>
				    {{ 'Total records:'|trans }} <span id="total"> {{ pagination.getTotalItemCount }} </span>
				</p>
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th>{{ knp_pagination_sortable(pagination, 'Title'|trans, 't.title') }}</th>
							<th>{{ knp_pagination_sortable(pagination, 'Date'|trans, 't.createdAt') }}</th>
							<th>{{ 'User'|trans }}</th>
							<th>{{ knp_pagination_sortable(pagination, 'Status'|trans, 't.status') }}</th>
							<th>{{ 'Actions'|trans }}</th>
						</tr>
					</thead>
					<tbody>
				        {% for task in pagination %}
				            <tr data-id="{{ task.id }}"> {# para trabajar con jquery #}
				                <td>
				                	<a href="{{ path('emm_task_view', { id: task.id }) }}">{{ task.title }}</a>
				                </td>
				                <td>{{ task.createdAt|date('d-m-Y H:i') }}</td>
				                <td>{{ task.user.firstName }} {{ task.user.lstaName }}</td>
				                <td>
				                	{% if task.status == 0 %}
										<span class="glyphicon glyphicon-time text-danger" title="Waiting" id="glyphicon-{{task.id}}"></span>
									{% elseif task.status == 1 %}
										<span class="glyphicon glyphicon-ok text-success" title="Finish"></span>
				                	{% endif %}
								</td>
								<td class="actions">
								    <a href="#" class="btn btn-sm btn-success btn-process" id="button-{{ task.id }}"> {# para usar en el ajax y ademas usamos el btn-process cada vez que hacemos click en el js verlo#}
								        {{ 'Finalize'|trans }}
								    </a>
								</td>
				            </tr>
				        {% endfor %}
					</tbody>
				</table>
			{# display navigation #}
			<div class="navigation">
			    {{ knp_pagination_render(pagination) }}
			</div>
			</div>
			{% endif %}
		</div>
	</div>
	
                {{ include('EMMUserBundle:User:forms/form.html.twig',{form:update_form,id:'form-update',with_submit:false,message:null}  )  }}  {# se pasa como nuell el mensaje ya que vamos a trabajar con ajz y no necesitamos#}
	
	
{% endblock %}

{% block javascripts %}
    {{ parent()}}
    <script src="{{asset('public/js/task-process.js')}}"></script>
     
    
{% endblock %}    

iglesia/src/EMM/UserBundle/Resources/views/Task/edit.html.twig
{%extends 'layout.html.twig'%}
{% block body %}
    {{parent()}}
    {{include('EMMUserBundle:Task:messages/success.html.twig')}}
    <div class="main container">
        <div class="row well">
            <div class="col-md-6">
                <div class="page-header">
                    <h2>Edit task</h2>
                </div>    
                
                {{form_start(form,{'attr':{'novalidate':'novalidate','role':'form'          }          }                        )              }}
                     <h4 class="text-danger">{{form_errors(form)}}</h4>
                     
                     <fieldset>
                         <div class="form-group">
                             {{form_label(form.title)}}
                             {{form_widget(form.title,{'attr':{ 'class':'form-control','playholder':'Task title'       }     }            )}}
                             <span class="text-danger">{{form_errors(form.title)}}<span>
                         </div>    
                         
                         <div class="form-group">
					        {{ form_label(form.user) }}
					        {{ form_widget(form.user, {'attr': {'class': 'form-control'}}) }}
					        <span class="text-danger">{{ form_errors(form.user) }}</span>
					    </div>

					    <div class="form-group">
					        {{ form_label(form.description) }}
					        {{ form_widget(form.description, {'attr': {'class': 'form-control', 'placeholder' : 'Task description'}}) }}
					        <span class="text-danger">{{ form_errors(form.description) }}</span>
                                            </div>
                         
                         
                     </fieldset>
                
                
                
                
                {{form_end(form)}}
            </div>
             <div class="col-md-6">
            </div>    
        </div>    
    </div> 
    
    
    
    
    
{% endblock %}    

iglesia/src/EMM/UserBundle/Resources/views/Task/index.html.twig
{% extends 'layout.html.twig' %}

{% block body %}
	{{ parent() }}
	
    {{ include('EMMUserBundle:Task:messages/success.html.twig') }}
    
	<div class="container">
		<div class="col-md-12">
			<div class="page-header margin-none">
				<h2 class="padding-none">{% trans %}Tasks{% endtrans %}</h2>
			</div>
			<div class="table-responsive">
				<p>
				    {% trans %}Total records: {% endtrans %} <span id="total"> {{ pagination.getTotalItemCount }} </span>
				</p>
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th>{{ knp_pagination_sortable(pagination, 'Title'|trans, 't.title') }}</th>
							<th>{{ knp_pagination_sortable(pagination, 'Date'|trans, 't.createdAt') }}</th>
							<th>{{ 'User'|trans }}</th>
							<th>{{ knp_pagination_sortable(pagination, 'Status'|trans, 't.status') }}</th>
						</tr>
					</thead>
					<tbody>
				        {% for task in pagination %}
				            <tr data-id="{{ task.id }}">
				                <td>
                                                    <a href="{{path('emm_task_view',{id:task.id})}}">{{task.title}}</a>
				                </td>
				                <td>{{ task.createdAt|date('d-m-Y H:i') }}</td>
				                <td>{{ task.user.fullName }}</td> {# parte intersante de asociaciones aca vemos q desde el campo task entramos al usuario y a su nombe compelto #}
				                <td>
				                	{% if task.status == 0 %}
										<span class="glyphicon glyphicon-time text-danger" title="{% trans %}Waiting{% endtrans %}" id="glyphicon-{{task.id}}"></span>
									{% elseif task.status == 1 %}
										<span class="glyphicon glyphicon-ok text-success" title="{% trans %}Finish{% endtrans %}"></span>
				                	{% endif %}
								</td>
				            </tr>
				        {% endfor %}
					</tbody>
				</table>
			{# display navigation #}
			<div class="navigation">
			    {{ knp_pagination_render(pagination) }}
			</div>
			</div>
		</div>
	</div>
{% endblock %}

iglesia/src/EMM/UserBundle/Resources/views/Task/view.html.twig
{% extends 'layout.html.twig' %}
{% block body %}
    {{parent()}}

    <div class="container well">
        <div class="row">
            <div class="col-md-9">
                <h2>{{task.title}}</h2>
                <br>
                <dl>
                    <dt>Description</dt>
                    <dd>
                        
                      {{task.description}}  
                    </dd>
                </dl>
                
                <br>
                <dl>
                    <dt>User</dt>
                    <dd>
                        
                        {{user.fullName}}
                    </dd>
                </dl>
                
                <br>
                <dl>
                    <dt>Status</dt>
                    <dd>
                        {% if task.status==0 %}
                          <span class="text-danger">Waiting</span>
                         {% elseif task.status==1 %}
                          <span class="text-success">Finish</span>
                          {% endif %}
                        
                    </dd>
                </dl>
                          
                 <br>
                <dl>
                    <dt>Created</dt>
                    <dd>
                        
                        {{task.createdAt|date('d-m-y H:i') }}
                    </dd>
                </dl>
                    
                    
                  <br>
                <dl>
                    <dt>Updated</dt>
                    <dd>
                        
                         {{task.updatedAt|date('d-m-y H:i') }}
                    </dd>
                </dl>  
                    
                          
            </div>
                    {% if is_granted('ROLE_ADMIN')%}
                    <div class="col-md-3">
                        <h3>Actions:</h3>
                        <p>
                        <a href="{{path('emm_task_edit',{id:task.id})}}" class="btn btn-primary btn-info btn-block">
                        <span class=" glyphicon glyphicon-edit"></span>
                        Edit Task
                        </a>
                        </p>
                        <p>
                            {{include('EMMUserBundle:Task:forms/form.html.twig',{form:delete_form,message:'Are you sure ?'})}}
                        </p>    
                    </div>        
                    {% endif %}

        </div>


    </div>    













{% endblock %}    